version: "3.3"

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: 42_nginx
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
    # links:
    #   - wordpress
    restart: always
  mariadb:
    container_name: 42_mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    restart: always
  # wordpress:
  #   container_name: wordpress
  #   build: ./requirements/wordpress
  #   networks:
  #     - inception
  #   ports:
  #     - "9000"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - mariadb
  #   links:
  #     - mariadb
  #   restart: always