version: "3.7"

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    env_file:
      - ./.env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/wordpress
    links:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/tnamir/data/mysql
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/tnamir/data/wordpress
      o: bind