version: "3.3"

networks:
  inception:
    driver: bridge

services:
  ngnix:
    container_name: nginx
    build: ./requirements/nginx
    # volumes:
      # -wordpress
    networks:
      - inception
    ports:
      - "443:443"
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    # volumes:
      # -wordpress