version: "3.3"

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - mariadb
    restart: always
    env_file:
      - ./.env
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    env_file:
      - ./.env
    depends_on:
      - mariadb
    # restart: always