version: "3.3"

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    env_file:
      - ./.env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www
    links:
      - mariadb
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/tnamir/data/mysql
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/tnamir/data/wordpress
      o: bind