version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    env_file:
      - ./.env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/tnamir/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/tnamir/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge