CREATE DATABASE '{$MARIADB_DATABASE}';
CREATE USER '{$MARIADB_USER}'@localhost IDENTIFIED BY '{$MARIADB_PASSWORD}';
GRANT all privileges ON '{$MARIADB_DATABASE}'.* TO '{$MARIADB_USER}'@localhost;
flush privileges;
ALTER USER '{$MARIADB_ROOT_USER}'@localhost IDENTIFIED BY '{$MARIADB_ROOT_PASSWORD}';